require("config.keymaps")
require("config.lazy") -- lazy must be loaded after leader is set inside require("keymaps")
require("config.netrw")
require("config.settings")
require("config.style")
require("config.commands")
require("config.highlight-commands")
