/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_LF_LF = 2,
  anon_sym_DASH = 3,
  anon_sym_PIPE = 4,
  anon_sym_DASH2 = 5,
  sym_day_identifier = 6,
  sym_note_title = 7,
  sym_identifier = 8,
  sym_list_bullet = 9,
  sym_note_content = 10,
  sym_year = 11,
  sym_number = 12,
  sym_source_file = 13,
  sym_day = 14,
  sym_time_entry = 15,
  sym_note_section = 16,
  sym_note = 17,
  sym_date = 18,
  sym_label_group = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_day_repeat1 = 21,
  aux_sym_time_entry_repeat1 = 22,
  aux_sym_note_section_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_LF_LF] = "\n\n",
  [anon_sym_DASH] = "-",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH2] = " - ",
  [sym_day_identifier] = "day_identifier",
  [sym_note_title] = "note_title",
  [sym_identifier] = "identifier",
  [sym_list_bullet] = "list_bullet",
  [sym_note_content] = "note_content",
  [sym_year] = "year",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_day] = "day",
  [sym_time_entry] = "time_entry",
  [sym_note_section] = "note_section",
  [sym_note] = "note",
  [sym_date] = "date",
  [sym_label_group] = "label_group",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_day_repeat1] = "day_repeat1",
  [aux_sym_time_entry_repeat1] = "time_entry_repeat1",
  [aux_sym_note_section_repeat1] = "note_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LF_LF] = anon_sym_LF_LF,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH2] = anon_sym_DASH2,
  [sym_day_identifier] = sym_day_identifier,
  [sym_note_title] = sym_note_title,
  [sym_identifier] = sym_identifier,
  [sym_list_bullet] = sym_list_bullet,
  [sym_note_content] = sym_note_content,
  [sym_year] = sym_year,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_day] = sym_day,
  [sym_time_entry] = sym_time_entry,
  [sym_note_section] = sym_note_section,
  [sym_note] = sym_note,
  [sym_date] = sym_date,
  [sym_label_group] = sym_label_group,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_day_repeat1] = aux_sym_day_repeat1,
  [aux_sym_time_entry_repeat1] = aux_sym_time_entry_repeat1,
  [aux_sym_note_section_repeat1] = aux_sym_note_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH2] = {
    .visible = true,
    .named = false,
  },
  [sym_day_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_note_title] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_list_bullet] = {
    .visible = true,
    .named = true,
  },
  [sym_note_content] = {
    .visible = true,
    .named = true,
  },
  [sym_year] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_day] = {
    .visible = true,
    .named = true,
  },
  [sym_time_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_note_section] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_label_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_day_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_time_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static const TSCharacterRange sym_note_content_character_set_1[] = {
  {' ', ' '}, {'(', ')'}, {',', ','}, {'.', '.'}, {'0', '9'}, {'A', '['}, {']', ']'}, {'_', '_'},
  {'a', 'z'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '2') ADVANCE(48);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '|') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(52);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '-') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(9);
      if (set_contains(sym_note_content_character_set_1, 9, lookahead)) ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(46);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'F') ADVANCE(26);
      if (lookahead == 'M') ADVANCE(25);
      if (lookahead == 'S') ADVANCE(15);
      if (lookahead == 'T') ADVANCE(21);
      if (lookahead == 'W') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'h') ADVANCE(31);
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 33:
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 34:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 37:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      END_STATE();
    case 38:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '2') ADVANCE(10);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '|') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LF_LF);
      if (lookahead == '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH2);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_day_identifier);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_note_title);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '0') ADVANCE(49);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_list_bullet);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_note_content);
      if (lookahead == ' ') ADVANCE(53);
      if (set_contains(sym_note_content_character_set_1, 9, lookahead)) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_note_content);
      if (set_contains(sym_note_content_character_set_1, 9, lookahead)) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_year);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 39},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_day_identifier] = ACTIONS(1),
    [sym_note_title] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_year] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_date] = STATE(13),
    [sym_year] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(7), 1,
      sym_list_bullet,
    STATE(3), 2,
      sym_note,
      aux_sym_note_section_repeat1,
    ACTIONS(5), 4,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
      sym_note_title,
  [14] = 3,
    ACTIONS(7), 1,
      sym_list_bullet,
    STATE(4), 2,
      sym_note,
      aux_sym_note_section_repeat1,
    ACTIONS(9), 4,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
      sym_note_title,
  [28] = 3,
    ACTIONS(13), 1,
      sym_list_bullet,
    STATE(4), 2,
      sym_note,
      aux_sym_note_section_repeat1,
    ACTIONS(11), 4,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
      sym_note_title,
  [42] = 4,
    ACTIONS(18), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      sym_label_group,
    ACTIONS(16), 2,
      ts_builtin_sym_end,
      sym_day_identifier,
    STATE(6), 2,
      sym_time_entry,
      aux_sym_day_repeat1,
  [57] = 4,
    ACTIONS(18), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      sym_label_group,
    ACTIONS(20), 2,
      ts_builtin_sym_end,
      sym_day_identifier,
    STATE(8), 2,
      sym_time_entry,
      aux_sym_day_repeat1,
  [72] = 3,
    ACTIONS(24), 1,
      sym_note_title,
    STATE(7), 2,
      sym_note_section,
      aux_sym_time_entry_repeat1,
    ACTIONS(22), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
  [85] = 4,
    ACTIONS(29), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      sym_label_group,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      sym_day_identifier,
    STATE(8), 2,
      sym_time_entry,
      aux_sym_day_repeat1,
  [100] = 3,
    ACTIONS(34), 1,
      sym_note_title,
    STATE(7), 2,
      sym_note_section,
      aux_sym_time_entry_repeat1,
    ACTIONS(32), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
  [113] = 3,
    ACTIONS(34), 1,
      sym_note_title,
    STATE(9), 2,
      sym_note_section,
      aux_sym_time_entry_repeat1,
    ACTIONS(36), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
  [126] = 1,
    ACTIONS(38), 5,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      sym_day_identifier,
      sym_note_title,
      sym_list_bullet,
  [134] = 3,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      sym_day_identifier,
    STATE(14), 2,
      sym_day,
      aux_sym_source_file_repeat1,
  [145] = 3,
    ACTIONS(42), 1,
      sym_day_identifier,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(12), 2,
      sym_day,
      aux_sym_source_file_repeat1,
  [156] = 3,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym_day_identifier,
    STATE(14), 2,
      sym_day,
      aux_sym_source_file_repeat1,
  [167] = 1,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      sym_day_identifier,
  [172] = 1,
    ACTIONS(53), 1,
      anon_sym_LF,
  [176] = 1,
    ACTIONS(55), 1,
      sym_number,
  [180] = 1,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
  [184] = 1,
    ACTIONS(59), 1,
      anon_sym_DASH,
  [188] = 1,
    ACTIONS(61), 1,
      anon_sym_DASH,
  [192] = 1,
    ACTIONS(63), 1,
      sym_number,
  [196] = 1,
    ACTIONS(65), 1,
      sym_identifier,
  [200] = 1,
    ACTIONS(67), 1,
      anon_sym_LF_LF,
  [204] = 1,
    ACTIONS(69), 1,
      sym_number,
  [208] = 1,
    ACTIONS(71), 1,
      sym_note_content,
  [212] = 1,
    ACTIONS(73), 1,
      anon_sym_PIPE,
  [216] = 1,
    ACTIONS(75), 1,
      anon_sym_DASH2,
  [220] = 1,
    ACTIONS(77), 1,
      anon_sym_LF_LF,
  [224] = 1,
    ACTIONS(79), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 57,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 85,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 113,
  [SMALL_STATE(11)] = 126,
  [SMALL_STATE(12)] = 134,
  [SMALL_STATE(13)] = 145,
  [SMALL_STATE(14)] = 156,
  [SMALL_STATE(15)] = 167,
  [SMALL_STATE(16)] = 172,
  [SMALL_STATE(17)] = 176,
  [SMALL_STATE(18)] = 180,
  [SMALL_STATE(19)] = 184,
  [SMALL_STATE(20)] = 188,
  [SMALL_STATE(21)] = 192,
  [SMALL_STATE(22)] = 196,
  [SMALL_STATE(23)] = 200,
  [SMALL_STATE(24)] = 204,
  [SMALL_STATE(25)] = 208,
  [SMALL_STATE(26)] = 212,
  [SMALL_STATE(27)] = 216,
  [SMALL_STATE(28)] = 220,
  [SMALL_STATE(29)] = 224,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_section, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_section, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_section_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_note_section_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day, 2, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day, 3, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_time_entry_repeat1, 2, 0, 0),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_time_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_day_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_day_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_entry, 3, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_entry, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 3, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date, 5, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [57] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_group, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_time_track(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "time_track",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
