-- Tests for parse_visual_reference via scriptures._parse_visual_reference
-- Run with: nvim --headless -u tests/minimal_init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua'}"

local assert = require("luassert")

-- We can require scriptures.init directly without calling setup()
-- since parse_visual_reference has no vim.api dependencies
local scriptures = require("scriptures.init")
local parse = scriptures._parse_visual_reference

describe("parse_visual_reference", function()

	describe("abbreviation format", function()
		it("parses book + chapter", function()
			local ref, err = parse("alma 32")
			assert.is_nil(err)
			assert.are.equal("bofm", ref.source_id)
			assert.are.equal("Alma", ref.book)
			assert.are.equal(32, ref.chapter)
			assert.is_nil(ref.verse)
		end)

		it("parses book + chapter + verse", function()
			local ref, err = parse("1ne 3:7")
			assert.is_nil(err)
			assert.are.equal("bofm", ref.source_id)
			assert.are.equal("1 Nephi", ref.book)
			assert.are.equal(3, ref.chapter)
			assert.are.equal(7, ref.verse)
		end)

		it("is case insensitive on abbreviation", function()
			local ref, err = parse("ALMA 5")
			assert.is_nil(err)
			assert.are.equal("Alma", ref.book)
			assert.are.equal(5, ref.chapter)
		end)

		it("handles D&C abbreviation", function()
			local ref, err = parse("dc 76")
			assert.is_nil(err)
			assert.are.equal("dc", ref.source_id)
			assert.are.equal("D&C", ref.book)
			assert.are.equal(76, ref.chapter)
		end)

		it("handles Old Testament abbreviation", function()
			local ref, err = parse("isa 53")
			assert.is_nil(err)
			assert.are.equal("ot", ref.source_id)
			assert.are.equal("Isaiah", ref.book)
			assert.are.equal(53, ref.chapter)
		end)

		it("handles New Testament abbreviation", function()
			local ref, err = parse("john 3")
			assert.is_nil(err)
			assert.are.equal("nt", ref.source_id)
			assert.are.equal("John", ref.book)
			assert.are.equal(3, ref.chapter)
		end)
	end)

	describe("full name format", function()
		it("parses multi-word book name + chapter", function()
			local ref, err = parse("1 Nephi 3")
			assert.is_nil(err)
			assert.are.equal("bofm", ref.source_id)
			assert.are.equal("1 Nephi", ref.book)
			assert.are.equal(3, ref.chapter)
		end)

		it("parses full name + chapter + verse", function()
			local ref, err = parse("Alma 32:23")
			assert.is_nil(err)
			assert.are.equal("Alma", ref.book)
			assert.are.equal(32, ref.chapter)
			assert.are.equal(23, ref.verse)
		end)

		it("is case insensitive on full name", function()
			local ref, err = parse("alma 32")
			assert.is_nil(err)
			assert.are.equal("Alma", ref.book)
		end)
	end)

	describe("whitespace handling", function()
		it("trims leading/trailing whitespace", function()
			local ref, err = parse("  alma 32  ")
			assert.is_nil(err)
			assert.are.equal("Alma", ref.book)
			assert.are.equal(32, ref.chapter)
		end)
	end)

	describe("invalid input", function()
		it("returns nil and error for unknown book", function()
			local ref, err = parse("xyz 5")
			assert.is_nil(ref)
			assert.is_not_nil(err)
		end)

		it("returns nil and error for missing chapter", function()
			local ref, err = parse("alma")
			assert.is_nil(ref)
			assert.is_not_nil(err)
		end)

		it("returns nil and error for empty string", function()
			local ref, err = parse("")
			assert.is_nil(ref)
			assert.is_not_nil(err)
		end)

		it("returns nil and error for non-numeric chapter", function()
			local ref, err = parse("alma abc")
			assert.is_nil(ref)
			assert.is_not_nil(err)
		end)
	end)
end)
